// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Token struct {
	ID        uuid.UUID      `json:"id"`
	Key       sql.NullString `json:"key"`
	Ident     sql.NullString `json:"ident"`
	CreatedAt time.Time      `json:"created_at"`
}
