// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: placeholder.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getPlaceholder = `-- name: GetPlaceholder :one
SELECT id, name, description, created_at FROM placeholder WHERE id=$1
`

func (q *Queries) GetPlaceholder(ctx context.Context, id uuid.UUID) (Placeholder, error) {
	row := q.db.QueryRowContext(ctx, getPlaceholder, id)
	var i Placeholder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
