// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rtc_description.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createRTCDescription = `-- name: CreateRTCDescription :exec
INSERT INTO
    rtc_description (token_id, sdp, type)
VALUES
    ($1, $2, $3)
`

type CreateRTCDescriptionParams struct {
	TokenID uuid.UUID `json:"token_id"`
	Sdp     string    `json:"sdp"`
	Type    RtcType   `json:"type"`
}

func (q *Queries) CreateRTCDescription(ctx context.Context, arg CreateRTCDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, createRTCDescription, arg.TokenID, arg.Sdp, arg.Type)
	return err
}

const deleteRTCDescription = `-- name: DeleteRTCDescription :exec
DELETE FROM rtc_description
WHERE
    token_id = $1
`

func (q *Queries) DeleteRTCDescription(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRTCDescription, tokenID)
	return err
}

const getRTCDescription = `-- name: GetRTCDescription :one
SELECT
    id, sdp, type, token_id, created_at
FROM
    rtc_description
WHERE
    token_id = $1
    AND type = $2
`

type GetRTCDescriptionParams struct {
	TokenID uuid.UUID `json:"token_id"`
	Type    RtcType   `json:"type"`
}

func (q *Queries) GetRTCDescription(ctx context.Context, arg GetRTCDescriptionParams) (RtcDescription, error) {
	row := q.db.QueryRowContext(ctx, getRTCDescription, arg.TokenID, arg.Type)
	var i RtcDescription
	err := row.Scan(
		&i.ID,
		&i.Sdp,
		&i.Type,
		&i.TokenID,
		&i.CreatedAt,
	)
	return i, err
}
