// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package repository

import (
	"context"
)

const validateToken = `-- name: ValidateToken :one
SELECT
    validate_token_key ($1)
`

func (q *Queries) ValidateToken(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, validateToken, key)
	var validate_token_key string
	err := row.Scan(&validate_token_key)
	return validate_token_key, err
}
