// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const validateToken = `-- name: ValidateToken :one
SELECT
    id,
    ident,
    created_at
FROM
    validate_token_key ($1)
`

type ValidateTokenRow struct {
	ID        uuid.UUID      `json:"id"`
	Ident     sql.NullString `json:"ident"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) ValidateToken(ctx context.Context, key string) (ValidateTokenRow, error) {
	row := q.db.QueryRowContext(ctx, validateToken, key)
	var i ValidateTokenRow
	err := row.Scan(&i.ID, &i.Ident, &i.CreatedAt)
	return i, err
}
