// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package repository

import (
	"context"
)

const getToken = `-- name: GetToken :one
SELECT
    validate_token_key ($1)
`

func (q *Queries) GetToken(ctx context.Context, key string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getToken, key)
	var validate_token_key interface{}
	err := row.Scan(&validate_token_key)
	return validate_token_key, err
}
